- hosts: all
  gather_facts: false
  become: true
  roles:
    - frps
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      register: selinux
    - name: Reboot
      ansible.builtin.reboot:
      when: selinux.reboot_required
